### ISSUE TITLE
[CLI] Allow project to define photo resize parameters

### ISSUE THREAD

**Issue by thomasboyt** [thomasboyt/nite-flights#34]

**Comment by thomasboyt** [comment]
settings.yml:

``` yaml
photos:
  sizes:
    - large:
      w: 1024
      h: 1024
    - small:
      w: 400
      h: 400
```

serialized photo object should look like:

``` json
{
  "sizes": {
    "large": "/path/to/large",
    "small": "/path/to/small"
  },
  "caption": "foo bar baz"
}
```
