### ISSUE TITLE
Add generic `meta` key for entries

### ISSUE THREAD

**Issue by thomasboyt** [thomasboyt/nite-flights#38]
Would be used for attaching additional data available in the _short_ form of serialized entries. Location is a good example of this:

```
- title: "Speedy Ortiz / Aye Nako"
  date: "2015-08-31"

  meta:
    location: "Saint Vitus"

  media: ...
  body: ...
  audio: ...
```

**Comment by thomasboyt** [comment]
another alternative this would be to have something like `short_fields` available in settings.yml:

``` yaml
entries:
  # These are additional keys that are available in the short-form version of posts used
  # as part of the post list.
  short_keys:
    - location
```
